// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R2A
// for U-VINNU\Vinnu (Vinnu@Vinnu) on Wed May 31 00:19:32 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "weatherPort.hh"

namespace WeatherSensor__to__Mobile {

weatherPort::weatherPort(const char *par_port_name)
	: weatherPort_BASE(par_port_name)
{

}

weatherPort::~weatherPort()
{

}

void weatherPort::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void weatherPort::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void weatherPort::Handle_Fd_Event_Error(int /*fd*/)
{

}

void weatherPort::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void weatherPort::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void weatherPort::Handle_Timeout(double time_since_last_call) {}*/

void weatherPort::user_map(const char * /*system_port*/)
{

}

void weatherPort::user_unmap(const char * /*system_port*/)
{

}

void weatherPort::user_start()
{

}

void weatherPort::user_stop()
{

}

void weatherPort::outgoing_send(const weatherRequest& /*send_par*/)
{

}

} /* end of namespace */

